# Matrix Operations

In [1]:
import numpy as np

In [2]:
a = np.array(([1, 2], [3, 4]))
b = np.array(([5, 6], [7, 8]))

#### Read a matrix

In [39]:
m = int(input("Nmber of rows:"))
n = int(input("Number of columns:"))

# Read a 1D list of size m * n, convert it to a numpy array and reshape it to m x n
matrix = np.array([int(input()) for _ in range(m * n)]).reshape(m, n)
matrix

array([[3, 5, 1],
       [6, 2, 7]])

#### 1. Dot Product

In [15]:
# Element-wise multiplication
a.dot(b)

array([[19, 22],
       [43, 50]])

#### 2. Transpose

In [14]:
# Swap the rows and columns
a.transpose()

array([[1, 3],
       [2, 4]])

#### 3. Flattened

In [13]:
# Convert 2D array to 1D array
a.flatten()

array([1, 2, 3, 4])

#### 3. Trace

In [20]:
# Sum of the diagonal elements
a.trace()

5

#### 4. Rank

In [24]:
np.linalg.matrix_rank(a)

2

#### 5. Determinant

In [17]:
np.linalg.det(a)

-2.0000000000000004

#### 6. Inverse

In [16]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### 7. Eigenvalues and Eigenvectors

In [33]:
res = np.linalg.eig(a)
res

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [37]:
print("Eigenvalues: ", res[0])
print("Eigenvectors:\n", res[1])

Eigenvalues:  [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [9]:
# Read a matrix
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of cols: "))
m = [[int(input("Element: ")) for _ in range(cols)] for _ in range(rows)]
print(m)

[[1, 2]]


In [14]:
# Read 2 matrices
m1 = int(input("Enter the number of rows: "))
n1 = int(input("Enter the number of cols: "))
matrix1 = np.asarray([np.asarray([int(input("Element: ")) for _ in range(n1)]) for _ in range(m1)])

m2 = int(input("Enter the number of rows: "))
n2 = int(input("Enter the number of cols: "))
matrix2 = np.asarray([np.asarray([int(input("Element: ")) for _ in range(n2)]) for _ in range(m2)])

print (matrix1)
print (matrix2)

[[1 2]
 [3 4]]
[[ 4  8]
 [16 32]]
