In [1]:
import numpy as np

In [4]:
a = np.array(([1, 2], [3, 4]))
b = np.array(([5, 6], [7, 8]))

In [12]:
print("Multiplication \n", a.dot(b))
print("Transpose \n", a.transpose())
print("Flattened (1D) \n", a.flatten())
print("Inverse \n", np.linalg.inv(a))
print("Determinant \n", np.linalg.det(a))


Multiplication 
 [[19 22]
 [43 50]]
Transpose 
 [[1 3]
 [2 4]]
Flattened (1D) 
 [1 2 3 4]
Inverse 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant 
 -2.0000000000000004
