# NumPy

NumPy (**Numerical Python**) is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently.

### Features

1. **N-Dimensional Array Object (ndarray)**: The core of NumPy is the `ndarray`, a fast and space-efficient multidimensional array providing vectorized operations.
2. **Mathematical Functions** to perform operations on arrays.
3. Functions for **Linear Algebra** operations.
4. **Random Number Generation**
5. **Integration with Other Libraries**, such as SciPy, Pandas, and Matplotlib.


> NumPy operations are implemented in C, making them much faster than standard Python loops.

In [8]:
import numpy as np

# Create a 1D array
a = np.array([1, 2, 3, 4, 5])
print("1D Array:", a)

# Create a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", b)

# Perform basic operations
sum_array = np.sum(a)
print("Sum of array:", sum_array)
mean_array = np.mean(a)
print("Mean of array:", mean_array)

# Perform element-wise addition
c = a + 10
print("Element-wise addition:", c)

# Matrix multiplication
d = np.dot(b, b.T)
print("Matrix multiplication:\n", d)

# Broadcasting: Perform operations on two arrays with different shapes
e = b + a[:3]
print("Broadcasting:\n", e)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Sum of array: 15
Mean of array: 3.0
Element-wise addition: [11 12 13 14 15]
Matrix multiplication:
 [[14 32]
 [32 77]]
Broadcasting:
 [[2 4 6]
 [5 7 9]]
